FROM postgres:latest

ENV POSTGRES_PASSWORD="REPLACE_THIS"
ENV POSTGRES_USER="root"
ENV POSTGRES_DB="dsaid"

RUN mkdir -p /docker-entrypoint-initdb.d
COPY ./db-init.sql /docker-entrypoint-initdb.d

EXPOSE 5432